// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoAnalisisClinica.Data;

#nullable disable

namespace ProyectoAnalisisClinica.Migrations
{
    [DbContext(typeof(ProyClinicaGuidoDbContext))]
    partial class ProyClinicaGuidoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateAppointment")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HourAppointment")
                        .HasColumnType("time");

                    b.Property<int>("MedicalPatientId")
                        .HasColumnType("integer");

                    b.Property<string>("OfficeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReasonAppointment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalPatientId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<double?>("BloodPressure")
                        .HasColumnType("double precision");

                    b.Property<string>("Diagnostic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReasonConsultation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Temperature")
                        .HasColumnType("integer");

                    b.Property<string>("TreatmentPlan")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Consultation", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Causes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsContagious")
                        .HasColumnType("boolean");

                    b.Property<string>("LevelSeverity")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TypeDisease")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Disease");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPatientDisease", b =>
                {
                    b.Property<int>("MedicalPatientId")
                        .HasColumnType("integer");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("integer");

                    b.HasKey("MedicalPatientId", "DiseaseId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("MedicalPatientDisease");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPrescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Observation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Emitida");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("MedicalPrescription", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicineInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<double?>("Concentration")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("NameMedicine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("PreparationDate")
                        .HasColumnType("date");

                    b.Property<string>("TypePresentation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MedicineInventory", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Phone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.PrescriptionMedicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DailyDose")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ItemObservation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MedicalPrescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineInventoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantityTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TreatmentDurationDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicineInventoryId");

                    b.HasIndex("MedicalPrescriptionId", "MedicineInventoryId");

                    b.ToTable("PrescriptionMedicine", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPatient", b =>
                {
                    b.HasBaseType("ProyectoAnalisisClinica.Models.Entities.Person");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Disability")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text");

                    b.Property<int>("EmergencyContactNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.ToTable("MedicalPatient", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.User", b =>
                {
                    b.HasBaseType("ProyectoAnalisisClinica.Models.Entities.Person");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasIndex("RolId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Appointment", b =>
                {
                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.MedicalPatient", "MedicalPatient")
                        .WithMany()
                        .HasForeignKey("MedicalPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalPatient");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Consultation", b =>
                {
                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.Appointment", "Appointment")
                        .WithOne("Consultation")
                        .HasForeignKey("ProyectoAnalisisClinica.Models.Entities.Consultation", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPatientDisease", b =>
                {
                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.Disease", "Disease")
                        .WithMany("MedicalPatientDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.MedicalPatient", "MedicalPatient")
                        .WithMany("MedicalPatientDiseases")
                        .HasForeignKey("MedicalPatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("MedicalPatient");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPrescription", b =>
                {
                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.Consultation", "Consultation")
                        .WithOne("MedicalPrescription")
                        .HasForeignKey("ProyectoAnalisisClinica.Models.Entities.MedicalPrescription", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.PrescriptionMedicine", b =>
                {
                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.MedicalPrescription", "MedicalPrescription")
                        .WithMany("Items")
                        .HasForeignKey("MedicalPrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.MedicineInventory", "Medicine")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicineInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalPrescription");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPatient", b =>
                {
                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("ProyectoAnalisisClinica.Models.Entities.MedicalPatient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.User", b =>
                {
                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("ProyectoAnalisisClinica.Models.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAnalisisClinica.Models.Entities.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Appointment", b =>
                {
                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Consultation", b =>
                {
                    b.Navigation("MedicalPrescription");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Disease", b =>
                {
                    b.Navigation("MedicalPatientDiseases");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPrescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicineInventory", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProyectoAnalisisClinica.Models.Entities.MedicalPatient", b =>
                {
                    b.Navigation("MedicalPatientDiseases");
                });
#pragma warning restore 612, 618
        }
    }
}
